### ISSUE TITLE
Please set your MNEMONIC in a .env file

### ISSUE THREAD

**Issue by DaveAppleton** [paulrberg/solidity-template#13]
As soon as I do a  `yarn compile` I get this error message.

Any chance of adding a note in the docs what we need to do?

e.g.

```
export MNEMONIC=test test test test test test test test test test test junk
export INFURA_API_KEY=....
```

**Comment by DaveAppleton** [comment]
ah - or just mention the `.env.example` file?

**Comment by paulrberg** [comment]
Hey @DaveAppleton, thanks for using my Solidity template!

The `.env.example` file is in version control due to this reason specifically, to show how to write content to a ".env". However, since this is the [second time](https://github.com/paulrberg/solidity-template/issues/5) someone opens an issue about the MNEMONIC env variable, I will mention it in the "Usage" section in the README.

**Comment by paulrberg** [comment]
Just updated the [Pre Requisites](https://github.com/paulrberg/solidity-template/tree/9d946d03afe412780b959a920903f8efa3bbe969#pre-requisites) section in the README to explain mnemonics.
