### ISSUE TITLE
Unclear why solidity bytecodeHash defaults to "none"

### ISSUE THREAD

**Issue by mds1** [paulrberg/solidity-template#31]
In [this commit](https://github.com/paulrberg/solidity-template/commit/ca577a52377a5a99ce3800609c79e68edda1055d#diff-57cf5378f8cab20b02b279097ba6fad08eb53f747d81770045dda9c5f95effe3) you wrote:

> // Do not include the metadata hash, since this is machine dependent and we want
> // all generated code to be deterministic.
> // https://docs.soliditylang.org/en/v0.7.6/metadata.html

From the linked docs it seems metadata is not machine dependent, but instead would be deterministic regardless of machine. I'd suggest either:

1. Removing this change to the solc settings if metadata is determistic
2. Adding a different link / better rationale if metadata is actually non-deterministic

**Comment by paulrberg** [comment]
I copied that part from [uniswap-v3](https://github.com/Uniswap/uniswap-v3-core/blob/2dc1eb9f251bad1c260d22dd392d8cedb2c6a4b5/hardhat.config.ts#L18-L22).

Admittedly, I didn't verify their claim, but anecdotally I resonated with it. I've encountered cases when the metadata changed unexpectedly, although I can't remember if that was due to using different machines or an undetected change of whitespaces in the source code.

Where in the docs did you find the explicit mention that the metadata hash is *not* machine dependent?

**Comment by mds1** [comment]
> I copied that part from uniswap-v3.

Ah, interesting! Wonder if @moodysalem can provide any extra context here then?

> Admittedly, I didn't verify their claim, but anecdotally I resonated with it. I've encountered cases when the metadata changed unexpectedly, although I can't remember if that was due to using different machines or an undetected change of whitespaces in the source code.

My understanding is that the metadata is expected to change from pretty much any "code" change, including whitespace changes, code comment changes, etc. So I'd guess what you saw was most likely due something like that

> Where in the docs did you find the explicit mention that the metadata hash is not machine dependent?

In the docs I didn't see any mention of whether or not the specific machine affects the metadata. It mentions many things that _do_ affect the metadata, but all of them were related to code/solc info, and none related to machine-specific into.

**Comment by moodysalem** [comment]
> My understanding is that the metadata is expected to change from pretty much any "code" change, including whitespace changes, code comment changes, etc. So I'd guess what you saw was most likely due something like that

In our experience it also changes based on absolute file paths, which means different machines will usually end up with different bytecode. May not be true for the latest versions of the compiler, but we don't feel it should be included in the bytecode either way.

**Comment by moodysalem** [comment]
> Thanks for info @moodysalem!
> 
> FWIW I tried testing the absolute filepath changes by cloning [this repo](https://github.com/gitcoinco/matching_contracts) this repo into two different file paths, bumping the solc version to 0.7.6 and comparing the bytecode of each. The bytecodes were identical, so perhaps it has been fixed in later solc versions, unless some other machine-specific data is getting in there
> 
> > but we don't feel it should be included in the bytecode either way.
> 
> In either case, this reasoning is fair enough!
> 
> @paulrberg it's your repo, so of course feel free to leave the defaults however you prefer 🙂

Could maybe the differences in operating systems/file endings? Not sure why else it would have differed in our testing. We ran into it last trying to validate bytecode was equivalent between our machines for the v2 deployment.

**Comment by paulrberg** [comment]
Thanks for the info, @moodysalem.

I went to the [Solidity Gitter server](https://gitter.im/ethereum/solidity) and posted the question there. Chris replied:

<img width="659" alt="Capture d’écran 2021-04-01 à 09 51 37" src="https://user-images.githubusercontent.com/8782666/113255001-f880ac80-92cf-11eb-9422-4da61051ae93.png">

Now, I am not yet sure what "not being careful with the paths" mean, I asked a follow-up question. But what it clear to me is that it is unclear how the metadata is computed. Folks like us who have been toying with Solidity for a while may be able to figure it out, but this template is intended to be used by everybody, including newcomers to Ethereum.

I will proceed with deleting the comment about the hash being machine-dependent, because that doesn't seem to be true. I will instead link to this GitHub issue, as an annotation for why that setting ending up there.

**Comment by mds1** [comment]
Looks like they replied to your follow up question, so just pasting the full convo here for posterity. Given that it's confirmed there is some machine/file path dependence, seems removing the metadata hash is the way to go if you want/need reproducible bytecode, which is a sensible default for a Solidity template.


![image](https://user-images.githubusercontent.com/17163988/113303398-e5f97980-92b5-11eb-89ec-bd4317cb3e17.png)
